apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-api
spec:
  selector:
    matchLabels:
      app: oncall-api
  template:
    metadata:
      labels:
        app: oncall-api
    spec:
      containers:
      - name: oncall-api
        image: oncall-api:v2
        ports:
        - containerPort: 80
